### PR TITLE
Add rules for Richie Bendall's Website

### PR DESCRIPTION
**Pull request by Richienb**

### CODE REVIEW

**Comment by davidfischer** [comment]
The rules in this PR are too generic and would potentially unblock Carbon/BuySellAds or Doubleclick across all sites. Your rules need to specifically reference the site where those should be unblocked (eg. https://www.richie-bendall.ml/).

**Comment by Richienb** [comment]
@davidfischer So, my domain is `richie-bendall.ml`. How do I change the rules so it only applies to it? The [ADP cheatsheet](https://adblockplus.org/filter-cheatsheet) hasn't been of much use to me.

**Comment by davidfischer** [comment]
Something like this should work well at least for Carbon. I didn't see any Google ads on your domain:

```
@@||carbonads.com^$domain=richie-bendall.ml
@@||carbonads.net^$domain=richie-bendall.ml
@@||buysellads.net^$domain=richie-bendall.ml
```


> The ADP cheatsheet hasn't been of much use to me.

The syntax here could be better documented for sure.

**Comment by Richienb** [comment]
@davidfischer Thanks! I'm going to fix the rules now.

**Comment by Richienb** [comment]
@davidfischer Done! Just for clarification, `doubleclick.net` is used by Carbon to count the number of times the ad loaded.

**Comment by davidfischer** [comment]
> Just for clarification, doubleclick.net is used by Carbon to count the number of times the ad loaded.

Ahhh true. I have seen that but only on Google ads served by Carbon. However, I'm sure that other advertisers on Carbon use that with Google Doubleclick Manager.

This looks good!

**Comment by Richienb** [comment]
Thanks!

**Pull request merged**
